"""Aggregate experiments/*/ANALYSIS.md one-line summaries into findings.md.

See specs/001-experiments-scaffolding/contracts/findings_aggregate_cli.md
and contracts/analysis_md_format.md.
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path

import typer
from rich.console import Console

from tradingagents.experiments.ids import ID_REGEX, parse_id

console = Console()
app = typer.Typer(add_completion=False)


@dataclass
class ExperimentRecord:
    """Aggregated state of one experiment for the index."""

    id: str
    date: str  # YYYY-MM-DD
    sequence: int
    slug: str
    summary: str | None
    state: str  # "completed" | "summary missing" | "pending analysis"
    has_analysis: bool


def _extract_summary(analysis_md: str) -> str | None:
    """Return the first non-empty line after the H1 and before any other heading.

    Per R-001 / contracts/analysis_md_format.md. Returns None if:
    - no `# ` heading found
    - no non-empty line between H1 and the next heading (or EOF)
    """
    lines = analysis_md.splitlines()
    in_h1_section = False
    for line in lines:
        stripped = line.strip()
        if not in_h1_section:
            if stripped.startswith("# ") and not stripped.startswith("##"):
                in_h1_section = True
            continue
        # We're past the H1.
        if not stripped:
            continue
        if stripped.startswith("#"):
            return None  # hit another heading without finding a summary
        return stripped
    return None


def _scan_experiment(exp_dir: Path) -> ExperimentRecord:
    """Build an ExperimentRecord for `exp_dir` (which is assumed to match ID_REGEX)."""
    id_str = exp_dir.name
    d, seq, slug = parse_id(id_str)
    analysis_path = exp_dir / "ANALYSIS.md"

    if not analysis_path.exists():
        return ExperimentRecord(
            id=id_str,
            date=d.isoformat(),
            sequence=seq,
            slug=slug,
            summary=None,
            state="pending analysis",
            has_analysis=False,
        )

    try:
        text = analysis_path.read_text(encoding="utf-8")
    except OSError:
        return ExperimentRecord(
            id=id_str,
            date=d.isoformat(),
            sequence=seq,
            slug=slug,
            summary=None,
            state="summary missing",
            has_analysis=True,
        )

    summary = _extract_summary(text)
    if summary is None:
        return ExperimentRecord(
            id=id_str,
            date=d.isoformat(),
            sequence=seq,
            slug=slug,
            summary=None,
            state="summary missing",
            has_analysis=True,
        )
    return ExperimentRecord(
        id=id_str,
        date=d.isoformat(),
        sequence=seq,
        slug=slug,
        summary=summary,
        state="completed",
        has_analysis=True,
    )


def _walk_experiments(experiments_dir: Path) -> list[ExperimentRecord]:
    """Walk `experiments_dir` for matching subdirs, return ExperimentRecords."""
    if not experiments_dir.exists():
        raise FileNotFoundError(f"Experiments directory not found: {experiments_dir}")
    records: list[ExperimentRecord] = []
    for entry in experiments_dir.iterdir():
        if not entry.is_dir():
            continue
        if not ID_REGEX.match(entry.name):
            continue
        try:
            records.append(_scan_experiment(entry))
        except (OSError, PermissionError) as e:
            console.print(f"[yellow]warning:[/yellow] could not read {entry}: {e}")
    # Sort newest first per R-002: (date DESC, sequence DESC).
    records.sort(key=lambda r: (r.date, r.sequence), reverse=True)
    return records


def _render_findings(records: list[ExperimentRecord]) -> str:
    """Render findings.md content from sorted records."""
    now = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    completed = sum(1 for r in records if r.state == "completed")
    pending = len(records) - completed

    lines: list[str] = []
    lines.append("# Findings")
    lines.append("")
    lines.append(
        "Living index of experiment one-line summaries. "
        "Auto-generated by `scripts/findings_aggregate.py` — do not edit by hand. "
        "To update: `python scripts/findings_aggregate.py`."
    )
    lines.append("")
    lines.append(f"Last updated: {now}")
    lines.append(f"Total experiments: {len(records)}")
    lines.append(f"Completed: {completed}")
    lines.append(f"Pending analysis: {pending}")
    lines.append("")
    lines.append("---")
    lines.append("")

    if not records:
        lines.append("> No experiments yet.")
        lines.append("")
        return "\n".join(lines)

    for r in records:
        date_seq = f"{r.date}-{r.sequence:03d}"
        lines.append(f"## {date_seq} — {r.slug}")
        lines.append("")
        if r.state == "completed":
            lines.append(f"> {r.summary}")
        elif r.state == "summary missing":
            lines.append("*summary missing — ANALYSIS.md exists but no extractable summary*")
        else:
            lines.append("*pending analysis*")
        lines.append("")
        # Links to per-experiment files.
        hyp_link = f"experiments/{r.id}/HYPOTHESIS.md"
        if r.has_analysis:
            ana_link = f"experiments/{r.id}/ANALYSIS.md"
            lines.append(f"[hypothesis]({hyp_link}) · [analysis]({ana_link})")
        else:
            lines.append(f"[hypothesis]({hyp_link})")
        lines.append("")

    return "\n".join(lines)


def _atomic_write(path: Path, content: str) -> None:
    """Write `content` to `path` atomically (tmp + rename)."""
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_text(content, encoding="utf-8")
    tmp.replace(path)


@app.command()
def main(
    experiments_dir: Path = typer.Option(
        Path("experiments"),
        "--experiments-dir",
        help="Where to walk for experiment subdirs.",
    ),
    out: Path = typer.Option(
        Path("findings.md"),
        "--out",
        help="Where to write the aggregated index.",
    ),
):
    """Walk experiments/ and write findings.md."""
    try:
        records = _walk_experiments(experiments_dir)
    except FileNotFoundError as e:
        console.print(f"[red]{e}[/red]")
        raise typer.Exit(1) from None

    content = _render_findings(records)
    _atomic_write(out, content)

    completed = sum(1 for r in records if r.state == "completed")
    pending = len(records) - completed
    console.print(
        f"Wrote {out} ({len(records)} experiments: {completed} completed, {pending} pending)"
    )


if __name__ == "__main__":
    app()
