"""Daily markdown digest renderer. Schema: ``contracts/digest_md.md``.

The first line of every digest is the verbatim Principle IV disclaimer
(asserted by ``tests/test_paper_digest.py::test_principle_iv_disclaimer_present``).
"""

from __future__ import annotations

from datetime import date
from decimal import Decimal
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from tradingagents.paper.engine import StepResult
    from tradingagents.paper.portfolio import Portfolio

DISCLAIMER = (
    "⚠️ **Simulation only — not financial advice.** This portfolio is paper-traded "
    "for research purposes. No real capital is involved. Past performance of "
    "simulated trades does not predict future results. Generated by "
    "`tradingagents-lab/scripts/paper_trade.py` (Constitution Principle IV)."
)

ZERO = Decimal("0")
HUNDRED = Decimal("100")
SPARK_BARS = "▁▂▃▄▅▆▇█"


def _fmt_dollar(x: Decimal) -> str:
    """Format Decimal as `$XXX,XXX.XX` (signed for negatives)."""
    sign = "-" if x < 0 else ""
    abs_x = abs(x)
    int_part, _, dec = f"{abs_x:.2f}".partition(".")
    int_with_commas = f"{int(int_part):,}"
    return f"{sign}${int_with_commas}.{dec}"


def _fmt_pct(x: Decimal, decimals: int = 2) -> str:
    """Format Decimal as `+X.XX%` (always signed)."""
    sign = "+" if x >= 0 else ""
    return f"{sign}{x:.{decimals}f}%"


def _equity_sparkline(equity_curve: list, n: int = 30) -> str:
    """Tiny Unicode sparkline of last n equity points."""
    points = equity_curve[-n:]
    if len(points) < 2:
        return "(insufficient history for sparkline)"
    values = [float(p.equity) for p in points]
    lo, hi = min(values), max(values)
    if hi == lo:
        return SPARK_BARS[0] * len(values)
    span = hi - lo
    out = []
    for v in values:
        bucket = int((v - lo) / span * (len(SPARK_BARS) - 1))
        out.append(SPARK_BARS[bucket])
    return "".join(out)


def _percent_change(start: Decimal, end: Decimal) -> Decimal:
    if start == ZERO:
        return ZERO
    return (end - start) / start * HUNDRED


def render_digest(
    portfolio: Portfolio,
    today: date,
    step_result: StepResult | None,
    mark_prices: dict[str, Decimal],
) -> str:
    """Render the full daily digest as a single markdown string.

    ``step_result`` may be None for pure-status invocations (US3) — sections
    that depend on today's events are then rendered as "_No trades today._".
    """
    lines: list[str] = []
    lines.append(DISCLAIMER)
    lines.append("")
    lines.append(f"# Paper-Trading Digest — `{portfolio.portfolio_id}` — {today.isoformat()}")
    lines.append("")

    equity = portfolio.equity(mark_prices)
    cash_pct = (portfolio.cash / equity * HUNDRED) if equity > ZERO else ZERO
    itd_return_pct = _percent_change(portfolio.starting_equity, equity)

    # Benchmark equity from latest equity_curve entry, if available
    bench_equity = (
        portfolio.equity_curve[-1].benchmark_equity
        if portfolio.equity_curve
        else portfolio.starting_equity
    )
    itd_bench_pct = _percent_change(portfolio.starting_equity, bench_equity)
    itd_alpha_pct = itd_return_pct - itd_bench_pct

    n_entries = len(step_result.entries) if step_result else 0
    n_exits = len(step_result.exits) if step_result else 0
    n_skips = len(step_result.skips) if step_result else 0

    lines.append("## Summary")
    lines.append("")
    lines.append("| Metric | Value |")
    lines.append("|---|---|")
    lines.append(f"| Equity | {_fmt_dollar(equity)} |")
    lines.append(f"| Cash | {_fmt_dollar(portfolio.cash)} ({_fmt_pct(cash_pct)}) |")
    lines.append(f"| ITD return | {_fmt_pct(itd_return_pct)} |")
    lines.append(f"| ITD α vs {portfolio.policy_snapshot.benchmark} | {_fmt_pct(itd_alpha_pct)} |")
    lines.append(
        f"| Open positions | {len(portfolio.positions)} of {portfolio.policy_snapshot.n_max_positions} |"
    )
    sectors = sorted({p.sector for p in portfolio.positions.values()})
    lines.append(f"| Sectors represented | {', '.join(sectors) if sectors else '_none_'} |")
    lines.append(f"| Today's events | {n_entries} entries, {n_exits} exits, {n_skips} skips |")
    lines.append("")

    # Today's trades
    lines.append("## Today's trades")
    lines.append("")
    if step_result and (step_result.entries or step_result.exits):
        lines.append("| Action | Ticker | Qty | Price | Sector | Reason |")
        lines.append("|---|---|---|---|---|---|")
        for pos in step_result.entries:
            lines.append(
                f"| OPEN | {pos.ticker} | {pos.qty} | {_fmt_dollar(pos.entry_price)} | "
                f"{pos.sector} | {pos.entry_rating} signal |"
            )
        for cp in step_result.exits:
            lines.append(
                f"| CLOSE | {cp.ticker} | {cp.qty} | {_fmt_dollar(cp.exit_price)} | "
                f"{cp.sector} | {cp.exit_reason} ({cp.actual_holding_days}d) |"
            )
    else:
        lines.append("_No trades today._")
    lines.append("")

    # Skipped entries
    if step_result and step_result.skips:
        lines.append("## Skipped entries")
        lines.append("")
        lines.append("| Ticker | Reason | Detail |")
        lines.append("|---|---|---|")
        for ev in step_result.skips:
            ticker = ev.payload.get("ticker", "?")
            reason = ev.payload.get("reason", ev.event_type.value)
            detail = ev.payload.get("detail", "")
            lines.append(f"| {ticker} | {reason} | {detail} |")
        lines.append("")

    # Open positions
    lines.append("## Open positions")
    lines.append("")
    if portfolio.positions:
        lines.append(
            "| Ticker | Sector | Entry | Days held | Entry $ | Mark $ | Unrealized $ | Unrealized % | Intended close |"
        )
        lines.append("|---|---|---|---|---|---|---|---|---|")
        for pos in sorted(portfolio.positions.values(), key=lambda p: p.entry_date):
            mark = mark_prices.get(pos.ticker, pos.entry_price)
            qty = Decimal(pos.qty)
            unrealized = (mark - pos.entry_price) * qty
            unrealized_pct = (mark - pos.entry_price) / pos.entry_price * HUNDRED
            days_held = (today - pos.entry_date).days
            lines.append(
                f"| {pos.ticker} | {pos.sector} | {pos.entry_date.isoformat()} | {days_held}d | "
                f"{_fmt_dollar(pos.entry_price)} | {_fmt_dollar(mark)} | "
                f"{_fmt_dollar(unrealized)} | {_fmt_pct(unrealized_pct)} | "
                f"{pos.intended_close_date.isoformat()} |"
            )
    else:
        lines.append("_No open positions._")
    lines.append("")

    # Recent closes
    if portfolio.closed:
        recent = sorted(portfolio.closed, key=lambda c: c.exit_date, reverse=True)[:20]
        lines.append("## Recent closes (last 20)")
        lines.append("")
        lines.append("| Ticker | Entry → Exit | Held | Reason | Raw % | α % |")
        lines.append("|---|---|---|---|---|---|")
        for cp in recent:
            raw_pct = cp.raw_return * HUNDRED
            alpha_pct = cp.alpha_return * HUNDRED
            lines.append(
                f"| {cp.ticker} | {cp.entry_date.isoformat()} → {cp.exit_date.isoformat()} | "
                f"{cp.actual_holding_days}d | {cp.exit_reason} | "
                f"{_fmt_pct(raw_pct)} | {_fmt_pct(alpha_pct)} |"
            )
        lines.append("")

    # Equity curve sparkline
    lines.append("## Equity curve (last 30 trading days)")
    lines.append("")
    spark = _equity_sparkline(portfolio.equity_curve, 30)
    lines.append("```")
    lines.append(spark)
    lines.append(
        f"{_fmt_dollar(portfolio.starting_equity)} → {_fmt_dollar(equity)}  "
        f"[{_fmt_pct(itd_return_pct)}]"
    )
    lines.append(f"Bench   {_fmt_pct(itd_bench_pct)}    α: {_fmt_pct(itd_alpha_pct)}")
    lines.append("```")
    lines.append("")

    # Policy snapshot
    snap = portfolio.policy_snapshot
    lines.append("## Policy snapshot")
    lines.append("")
    lines.append("```")
    lines.append(f"{snap.policy_version}")
    lines.append(f"holding_window: {snap.holding_window_trading_days} trading days")
    lines.append(f"n_max_positions: {snap.n_max_positions}")
    lines.append(f"target_per_position: {snap.target_per_position_pct}%")
    lines.append(f"cash_buffer: {snap.cash_buffer_pct}%")
    lines.append(f"per_sector_cap: {snap.per_sector_cap_pct}%")
    lines.append(f"per_position_cap: {snap.per_position_cap_pct}%")
    lines.append(
        f"slippage: {snap.entry_slippage_bps} bps entry / {snap.exit_slippage_bps} bps exit"
    )
    lines.append(f"benchmark: {snap.benchmark}")
    lines.append("```")

    return "\n".join(lines) + "\n"


def digest_filename(portfolio_id: str, target_date: date) -> str:
    """Standard digest filename: ``paper-<id>-<date>.md``."""
    return f"paper-{portfolio_id}-{target_date.isoformat()}.md"
